backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title (English)", name: "title_en", widget: "string" }
      - { label: "Title (Arabic)", name: "title_ar", widget: "string" }
      - { label: "Price (QAR)", name: "price", widget: "number" }
      - { label: "Delivery Charge (QAR)", name: "delivery", widget: "number", default: 30 }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Product Image", name: "image", widget: "image" }
